/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;

import controller.Controller;
import defaultname.SectionComponent;
import defaultname.SectionComposite;

/**
 *
 * @author Leg
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */

    private Controller controller;
    private final int LEFT_CLICK = 1;
    private final int RIGHT_CLICK = 3;
    private DefaultMutableTreeNode lastNodeUsed; //va servir pour sauvegarder le texte dans les sections et sous-sections
    
    public MainView(Controller controller) {
        initComponents();
        this.controller = controller;       
    }

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        addSubSectionButton = new javax.swing.JButton();
        addSectionButton = new javax.swing.JButton();
        
        jTreePopupMenu = new javax.swing.JPopupMenu();
        addSectionMenuItem = new javax.swing.JMenuItem();
        addSubSectionMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("SectionsRegister");
        jTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        
        jTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTreeMouseClicked(evt);
            }
        });
        
        jScrollPane1.setViewportView(jTree);

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane2.setViewportView(jTextArea);
        
        
        addSectionMenuItem.setText("add Section");
        addSectionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSectionMenuItemActionPerformed(evt);
            }
        });
        jTreePopupMenu.add(addSectionMenuItem);

        addSubSectionMenuItem.setText("add SubSection");
        addSubSectionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubSectionMenuItemActionPerformed(evt);
            }
        });
        jTreePopupMenu.add(addSubSectionMenuItem);

        deleteMenuItem.setText("delete");
        deleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemActionPerformed(evt);
            }
        });
        jTreePopupMenu.add(deleteMenuItem);
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addSectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addSubSectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSubSectionButton)
                    .addComponent(addSectionButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void addSectionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                   
    	DefaultTreeModel model = (DefaultTreeModel) jTree.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        root.add(new DefaultMutableTreeNode(controller.addSection()));
        model.reload(root);  
    }                                                  

    private void addSubSectionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                      
    	TreeSelectionModel selectionModel = jTree.getSelectionModel();
        TreePath selectionPath = selectionModel.getSelectionPath();
        DefaultMutableTreeNode node = (DefaultMutableTreeNode)selectionPath.getLastPathComponent();
        DefaultTreeModel model = (DefaultTreeModel) jTree.getModel();
        SectionComposite section = (SectionComposite)node.getUserObject();

        node.add(new DefaultMutableTreeNode(controller.addSubSection(section.getId())));
        model.reload(node);
    }                                                     

    private void deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                               
        System.out.println("IMPLÉMENTEZ LE DELETE!");
    }   
    
    private void jTreeMouseClicked(java.awt.event.MouseEvent evt) {                                    
        
    	System.out.println("Last node used " + lastNodeUsed);
    	if(lastNodeUsed != null){
    		if(!lastNodeUsed.getUserObject().getClass().toString().equals("class java.lang.String")){
    			SectionComponent sectionComponent = (SectionComponent)lastNodeUsed.getUserObject();
    			controller.saveText(sectionComponent.getId(), jTextArea.getText());
    		}
    		System.out.println(lastNodeUsed.getUserObject().getClass());
    	}
    	TreeSelectionModel selectionModel = jTree.getSelectionModel();
    	TreePath selectionPath = selectionModel.getSelectionPath();
    	DefaultMutableTreeNode node = (DefaultMutableTreeNode)selectionPath.getLastPathComponent();
    	
    	lastNodeUsed = node;
    	
        if(evt.getButton() == LEFT_CLICK){
             
            try{
            	SectionComponent sectionComponent = (SectionComponent)node.getUserObject();
            	String currentText = controller.getContent(sectionComponent.getId());
            	jTextArea.setText(currentText);
            	
            }catch(Exception e){
            	System.out.println("Petit bug à fix, le root va devoir être un SectionComposite et non une String");
            }
            
          
        	
        }else if(evt.getButton() == RIGHT_CLICK){
        
        	jTreePopupMenu.show(this, evt.getX(), evt.getY());
        	
        }
        
        

           
    	
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        
//        
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSectionButton;
    private javax.swing.JButton addSubSectionButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTree jTree;
    private javax.swing.JPopupMenu jTreePopupMenu;
    private javax.swing.JMenuItem addSectionMenuItem;
    private javax.swing.JMenuItem addSubSectionMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    // End of variables declaration//GEN-END:variables

  

}


